[tool.bandit]
skips = ["B101", "B104", "B105", "B106", "B107", "B108", "B110"]
exclude_dirs = ["tests", "docs"]
confidence-level = "medium"

[tool.black]
line-length = 88
target-version = ["py38"]
include = '\.pyi?$'

[tool.isort]
profile = "black"
multi_line_output = 3
include_trailing_comma = true

[tool.mypy]
python_version = "3.12"
warn_return_any = false
warn_unused_configs = true
disallow_untyped_defs = false
check_untyped_defs = false
ignore_missing_imports = true
exclude = ["tests/*", "docs/*"]

[tool.safety]
ignore-vulnerabilities = []
ignore-cvss-severity-below = 7  # Only high and critical

[tool.semgrep]
config = ["p/aws"]  # Focus only on AWS-related security checks
exclude = ["tests/*", "docs/*"]
severity = "ERROR"
